packages:
  - apps/*
  - packages/*
catalogs:
  prisma:
    prisma: latest
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - prisma
  - sharp
